name: Laravel
on:
  push:
    branches: [ "main" ]
env:
  SERVER_HOST: 5.35.90.138
  SERVER_USER: root
  SERVER_PATH: ../var/www/TelegramApi
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v2
      - name: Install composer
        run: composer install
      - name: Npm install
        run: npm install
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
  laravel-push:
    needs: [laravel-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH KEY
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: "${{ secrets.TELEGRAM_API }}"
          known_hosts: "your_server_public_key"
      - name: Generate auth hosts
        run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts
      #Deploy
      - run: rsync --archive --compress --progress . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{env.SERVER_PATH}}
      - name: Update composer and install npm on the server
        run: ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "cd ${{ env.SERVER_PATH }}  &&  composer install --ignore-platform-reqs  && npm install"
      - name: Directory Permissions
        run: ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "cd ${{ env.SERVER_PATH }} && chmod -R 777 storage bootstrap/cache"
      - name: Octane
        run: ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "cd ${{ env.SERVER_PATH }} && pm2 restart all"

